name: 'OpenAPI Performance Test'
description: 'Automatically Performance Test OpenAPI Endpoints'
branding:
  icon: bar-chart-2
  color: gray-dark
inputs:
  openapi-endpoint:
    description: 'The URL of the openapi schema under test'
    required: true
    default: 'http://localhost:5000/openapi.json'
runs:
  using: 'docker'
  image: 'Dockerfile'