name: 'OpenAPI Performance Test'
description: 'Automatically Performance Test OpenAPI Endpoints'
branding:
  icon: bar-chart-2
  color: gray-dark
inputs:
  openapi-endpoint:
    description: 'The URL of the openapi schema under test'
    required: true
    default: 'http://localhost:5000/openapi.json'
  token:
    description: 'Github token allowing posting of comments'
    required: true
runs:
  using: 'docker'
  pre-if: ${{ github.actor }} != 'openapi-performance-testing[bot]'
  image: docker://awtkns/openapi-perf-action:latest
