on: pull_request

jobs:
  openapi-perf:
    name: Builds and Runs the OpenAPI Performance Test Action
    runs-on: ubuntu-latest
    steps:
    - name: OpenAPI Performance Test
      uses: awtkns/openapi-perf-action@main
      with:
        openapi-endpoint: 'http://localhost:5000/'
